platform :ios, '7.0'

pod 'RESideMenu', '~> 4.0.7'
pod 'MBProgressHUD'
pod 'SSKeychain'
pod 'HPGrowingTextView'
pod 'LTUpdate', '~> 0.0.2'
pod 'SDWebImage', '~>3.6'
pod 'pop', '~> 1.0'
pod "AFNetworking", "~> 2.0"
pod 'MWPhotoBrowser'
pod 'DZNEmptyDataSet'
pod 'PBWebViewController'
pod 'RegexKitLite', '~> 4.0'
pod 'JDStatusBarNotification'
pod 'StreamingKit', '~> 0.1.25'